### ISSUE TITLE
Add a Sentiment Analysis Implementation with Go Library and Improve Algorithm to be more accurate

### ISSUE THREAD

**Issue by Corrob** [arianht/meantweets#4]
https://github.com/cdipaolo/sentiment

**Comment by arianht** [comment]
Added an implementation based on cdipaolo's package. We will have to evaluate the results and maybe look at other options.

**Comment by Corrob** [comment]
You can use the crawler integration test to check results. A possible improvement I noticed was taking into account tweet length such as using a sum instead of an average.

**Comment by Corrob** [comment]
Updating the library to provide a probability seems to improve results. Also, we could train the model on a twitter dataset: http://cs.stanford.edu/people/alecmgo/trainingandtestdata.zip

**Comment by Corrob** [comment]
Closing to be re-assessed in the future. We can create a new issue describing the issues of the current sentiment analysis after running in production for a while.
